/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.resume.panel;

import com.company.resume.config.Config;
import com.mycompany.entity.User;

/**
 *
 * @author hp
 */
public class EmploymentHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmploymentHistoryPanel
     */
    public EmploymentHistoryPanel() {
        initComponents();
    }
          public void fillUserComponents() {
        User loggedInUser = Config.loggedInUser;
        txtEmplHistory.setText(loggedInUser.getEmploymentHistory());
       
    }
        public void fillUser(User user){
            user.setEmploymentHistory(txtEmplHistory.getText());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEmplHistory = new javax.swing.JTextArea();

        txtEmplHistory.setColumns(20);
        txtEmplHistory.setRows(5);
        jScrollPane1.setViewportView(txtEmplHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEmplHistory;
    // End of variables declaration//GEN-END:variables
}
